When the checker is loading a page or trying to find the question that someone
submitted to, there are rare cases where an error can occur.  Right now, the UI
continues to report that "your submission is currently being checker" in that
case, which is not true (since the error means we can't even start checking in
that case).    Example: 6.009 staff trying to submit `'q000000'` as a student,
but the student doesn't actually have that box because `cs_post_load` removes it
from their view.    Server reports:

    Process Process-173:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
        self.run()
      File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
        self._target(*self._args, **self._kwargs)
      File "checker.py", line 148, in do_check
        question, args = namemap[name]
    KeyError: 'q000000'
